name: Ejecucion Automatizada de Ingesta

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # AGREGA ESTAS LÍNEAS AQUÍ:
    permissions:
      contents: write

    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v3
# ... (el resto del archivo sigue igual)
      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Ejecutar script de ingesta
        run: |
          chmod +x ./scripts/ingesta.sh
          ./scripts/ingesta.sh  